from builtins import object

import urllib3.packages.six
from selenium.webdriver.common.by import By

"""
Objects are Separated in this module
 - ID is the preferable choice as it is unique in a web page
 - XPATH is the next best alternative and is also unique but it is cumbersome to fix 
   if the there are any changes in the layout of the Web page.
- Add the Identifiers in Tuple.
"""


class RegistrationPageIdentifiers(object):
    """
    This class holds the User Registration Page Identifiers
    """
    REGISTER = (By.XPATH, '/html/body/div[1]/div/header/div[3]/div[1]/button[2]/span')
    FIRST_NAME = (By.ID, 'registration_first_name')
    LAST_NAME = (By.ID, 'registration_last_name')
    EMAIL = (By.ID, 'registration_email')
    PASSWORD = (By.ID, 'registration_password')
    MOBILE_NUMBER = (By.ID, 'registration_phone')
    CONFIRM_PASSWORD = (By.ID, 'registration_confirm')
    CLOSE_ICON = (By.ID, 'register-modal-close-btn')
    CAPTCHA = (By.ID, 'recaptcha-anchor')
    LOGIN_HERE = (By.ID, 'already-text-link')
    TITLE = (By.ID, 'registration-title')
    LOGIN_TITLE = (By.XPATH, '//h2[@class="ant-typography Login_titles__nmC2y"]')
    REGISTER_NOW = (By.ID, 'register-btn')
    ERROR_FIRST_NAME = (By.ID, "registration_first_name_help")
    ERROR_LAST_NAME = (By.ID, 'registration_last_name_help')
    ERROR = (By.XPATH, '//div[@class="ant-form-item-explain-error"]')
    ERROR_PASSWORD = (By.ID, 'registration_password_help')
    ERROR_MOBILE_NUMBER = (By.ID, 'registration_phone_help')
    ERROR_CONFIRMATION_PASSWORD = (By.ID, 'registration_confirm_help')
    ERROR_EMAIL = (By.ID, 'registration_email_help')
    ERROR_CAPTCHA = (By.ID, 'registration_captcha_help')
    FIRST_NAME_ASTRK = (By.XPATH, '(//span[@class = "required"])[1]')
    LAST_NAME_ASTRK = (By.XPATH, '(//span[@class = "required"])[2]')
    EMAIL_ASTRK = (By.XPATH, '(//span[@class = "required"])[3]')
    PASSWORD_ASTRK = (By.XPATH, '(//span[@class = "required"])[4]')
    CONFIRM_PASSWORD_ASTRK = (By.XPATH, '(//span[@class = "required"])[5]')


class LoginPageIdentifiers(object):
    EMAIL_ASTRK = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div/div[1]/label/span')
    PASSWORD_ASTRK = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[2]/div/div[1]/label/span')
    LOGIN_BUTTON = (By.ID, 'login-btn')
    EMAIL = (By.ID, 'login_form_username')
    PASSWORD = (By.ID, 'login_form_password')
    SUBMIT = (By.ID, 'login-btn')
    CLOSE_BUTTON = (By.ID, 'modal-close-btn')
    CHECK_BOX = (By.ID, 'login_form_remember')
    INVALID_EMAIL_TITLE = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div[1]/div[2]/div[2]/div[1]/div')
    BLANK_EMAIL_ERROR = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]')
    BLANK_PASSWORD_ERROR = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[2]/div[1]/div[2]/div[2]/div[1]/div')
    ONE_TIME_REQUEST_TITLE = (By.ID, 'otp-title-text')
    FORGET_PASSWORD = (By.XPATH, '/html/body/div[2]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[3]/div/div/div/div/a')
    FORGET_PASSWORD_TITLE = (By.XPATH, '//h2[text()= "Forgot your password?"]')
    REGISTER_NOW_LINK = (By.ID, 'register-btn')
    REQUEST_CODE = (By.ID, 'request-otp-btn')
    EMAIL_ERROR_MESSAGE = (By.XPATH, '//*[@id="login_form"]/div[1]/div[2]/div[2]/div')
    LOGIN_TITLE = (By.XPATH, '//h2[@class="ant-typography Registration_titles__pUOnj"]')
    SOCIAL_LINKS = (By.XPATH, '//div[@class="social-login_btn_group__BQdOr"]//child::button')
    FACEBOOK_LINK = (By.ID, 'facebook-link')
    FACEBOOK_TITLE = (By.ID, 'header_block')
    GOOGLE_LINK = (By.ID, 'google-link')
    GOOGLE_TITLE = (By.XPATH, '//div[text()="Sign in with Google"]')
    TWITTER_LINK = (By.ID, 'twitter-link')
    TWITTER_TITLE = (By.XPATH, '//strong[text()="This application will be able to:"]')
    LINKEDIN_LINK = (By.ID, 'linkedin-link')
    LINKEDIN_SIGNIN = (By.XPATH, "/html/body/div/main/div[2]/form/div[3]/button")
    LINKEDIN_TITLE = (By.CLASS_NAME, 'header__content__heading ')
    GITHUB_SIGNIN = (By.XPATH, "/html/body/div[1]/div[3]/main/div/div[3]/form/div/input[12]")
    GITHUB_LINK = (By.ID, 'github-link')	
    GITHUB_TITLE = (By.XPATH, '//*[@id="js-pjax-container"]/div/div[1]/h2')
    BROWSE = (By.XPATH, '/html/body/div[1]/div/header/div[2]/nav/ul/li[1]/a/text()')
    EMAIL_ASTRK = (By.XPATH, '//span[@class = "required"]')
    PASSWORD_ASTRK = (By.XPATH, '(//span[@class = "required"])[2]')
    LOGIN_BUTTON = (By.XPATH, '//*[@id="__next"]/div/header/div[3]/div[1]/button[1]/span')
    EMAIL = (By.ID, 'login_form_username')
    PASSWORD = (By.ID, 'login_form_password')
    SUBMIT = (By.ID, 'login-btn')
    CLOSE_BUTTON = (By.XPATH, '//span[@class = "anticon anticon-close-circle"]')
    CHECK_BOX = (By.ID, 'login_form_remember')
    INVALID_EMAIL_TITLE = (By.XPATH, '/html/body/div[2]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div[1]/div[2]/div[2]/div[1]/div')
    BLANK_EMAIL_ERROR = (By.XPATH, '/html/body/div[2]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]')
    BLANK_PASSWORD_ERROR = (By.XPATH, '//div[text() = "Please input your Password!"]')
    ONE_TIME_REQUEST_TITLE = (By.XPATH, '//h2[@class = "ant-typography Registration_titles__pUOnj"]')
    FORGET_PASSWORD = (By.XPATH, '//a[text()= "Forgot password"]')
    FORGET_PASSWORD_TITLE = (By.XPATH, '//h2[text()= "Forgot your password?"]')
    REGISTER_NOW_LINK = (By.ID, 'dont-account-link-tag')
    REQUEST_CODE = (By.ID, 'request-otp-btn')
    EMAIL_ERROR_MESSAGE = (By.XPATH, '/html/body/div[2]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]')
    LOGIN_TITLE = (By.XPATH, '//*[@id="registration-title"]')
    SOCIAL_LINKS = (By.XPATH, '//div[@class="social-login_btn_group__BQdOr"]//child::button')
    FACEBOOK_LINK = (By.ID, 'facebook-link')
    FACEBOOK_TITLE = (By.ID, 'header_block')
    GOOGLE_LINK = (By.ID, 'google-link')
    TWITTER_LINK = (By.ID, 'twitter-link')
    TWITTER_TITLE = (By.XPATH, '//h2[text() = "Authorize the_canonizer to access your account?"]')
    LINKEDIN_LINK = (By.ID, 'linkedin-link')
    LINKEDIN_TITLE = (By.XPATH, '//*[@id="app__container"]/main/div[2]/div[2]')
    GITHUB_LINK = (By.ID, 'github-link')
    GITHUB_TITLE = (By.XPATH, '//*[@id="js-pjax-container"]/div/div[1]/h2')


class ProfileInfoIdentifiersPage(object):
    CLICK_ON_DROPDOWN = (By.XPATH, '//*[@id="__next"]/div/header/div[3]/div[1]/div/div/div[2]/div/div[3]/a')
    PROFILE_BUTTON = (By.ID, 'rc-tabs-0-tab-profile_info')
    ACCOUNT_SETTING_BUTTON = (By.XPATH, '/html/body/div[2]/div/div/ul/li[1]/span')
    SOCIAL_OAUTH_VERIFICATION = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[2]/div')
    CHANGE_PASSWORD = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[3]/div')
    SUPPORTED_CAMPS = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[5]/div')
    NICK_NAME = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[4]/div')
    PHONE_NUMBER = (By.ID, 'phoneNumber')
    PHONE_NUMBER_ERROR = (By.XPATH, '/div/div/div/span[2]')
    MOBILE_CARRIER = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[2]/section/section/form/div/div[1]/div[2]/div/div/div[2]/div/div/div/div/span[1]/input')
    VERIFY_BUTTON = (By.ID, 'verifyBtn')
    FIRST_NAME = (By.ID, 'firstName')
    MIDDLE_NAME = (By.ID, 'middleName')
    LAST_NAME = (By.ID, 'lastName')
    GENDER = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div[2]/div/div/div[2]/section/form/div[1]/div[1]/div[5]/div/div/div[2]/div/div/div/div/div[1]/label/span[1]/input')
    DATA_BIRTH = (By.ID, 'profileInfo_birthday')
    UPDATE_BUTTON = (By.XPATH, '//span[text() = "Update"]')
    LOGOUT = (By.XPATH, '//span[text()="Log Out"]')
    ADDRESS_LINE = (By.ID, 'selectAddress_1')
    ALGORITHM_FIELD = (By.XPATH, '/html/body/div[2]/div/div/div/div[2]/div[1]/div/div/div[5]/div')
    ALGORITHM_DROP_DOWN = (By.XPATH, '(//div[@class="ant-select-item-option-content"])[1]')


class CanonizerSupportCampIdentifiersPage(object):
    CLICK_ON_DROPDOWN = (By.XPATH, '//*[@id="__next"]/div/header/div[3]/div[1]/div/div/div[2]/div/div[3]/a')
    ACCOUNT_SETTING_BUTTON = (By.XPATH, '(//span[@class="ant-dropdown-menu-title-content"])[1]')
    SUPPORTED_CAMPS = (By.XPATH, '//div[text()="Direct Supported Camps"]')
    DIRECT_SUPPORTED_CAMPS = (By.XPATH, '//div[text()="Direct Supported Camps"]')
    DELEGATED_SUPPORT_CAMPS = (By.XPATH, '//div[text()="Delegated Support Camps"]')
    SUPPORT_CAMP_SEARCH_BAR = (By.XPATH, '//div [@class = "Settings_search_users__sjo27"]')
    CLICKING_ON_TOPIC_NAME = (By.XPATH, '(//div [@class = "DirectSupportedCamps_card_heading_title__qF4nl"])[1]')
    TOPIC_NAME_TITLE = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/div/div[1]/div[1]/div[1]')
    CLICK_ON_REMOVE_SUPPORT = (By.XPATH, '//div[@class="ant-card-extra"]//child::div')
    REMOVE_ON_POP_UP_BUTTON = (By.ID, 'removeBtn')
    REMOVE_TITLE = (By.XPATH, '//div[@class="ant-modal-title"]')
    SUPPORTED_CAMP_TITLE = (By.CLASS_NAME, 'Settings_notes__KNmaY')
    SUPPORTED_CAMP_DROPDOWN = (By.XPATH, '(//a[@href="/settings?tab=supported_camps"])[2]')
    NICK_NAME_LINK = (By.XPATH, '(//a[@class="DelegatedSupportedCamps_Bluecolor__wZ9Xe"])[2]')
    SUPPORT_DELEGATED_TO_LINK = (By.XPATH, '//a[@class="DelegatedSupportedCamps_Bluecolor__wZ9Xe"]')
    CURRENT_SUPPORTED_CAMP = (By.XPATH, '(//a[@class="DelegatedSupportedCamps_Bluecolor__wZ9Xe"])[3]')
    DELEGATED_SUPPORT_CAMP_LINK = (By.XPATH, '//div[@class="DelegatedSupportedCamps_card_heading_title__dPHEd"]//a[1]')
    NICK_NAME_COMPARE = (By.XPATH, '//span[@class="UserProfile_Bluecolor__El2lJ"]//b[1]')
    AGREEMENT_CAMP = (By.XPATH, '//div[@class="topicDetails_breadcrumbLinks__7BG2D"]//a[1]')
    AGREEMENT_DIRECT_SUPPORT_LINK = (By.XPATH,'//a[@class="DirectSupportedCamps_Bluecolor__Q2ZFH"]')
    TOPIC_LINK = (By.XPATH, '//div[@class="DirectSupportedCamps_card_heading_title__qF4nl"]//a')
    DIRECT_SUPPORTED_CAMP_LINK = (By.XPATH, '//span[@class="treeListItemTitle topicDetails_treeListItemTitle__G91mC"]//a[1]')


class CanonizerChangePasswordIdentifierPage(object):
    CLICK_ON_DROPDOWN = (By.XPATH, '//*[@id="__next"]/div/header/div[3]/div[1]/div/div/div[2]/div/div[3]/a')
    ACCOUNT_SETTING_BUTTON = (By.XPATH, '(//span[@class="ant-dropdown-menu-title-content"])[1]')
    CHANGE_PASSWORD = (By.XPATH, '(//div[@class="ant-tabs-tab-btn"])[3]')
    CURRENT_PASSWORD = (By.ID, 'currentPassword')
    NEW_PASSWORD = (By.ID, 'newPassword')
    CONFIRM_PASSWORD = (By.ID, 'confirmPassword')
    SAVE_BUTTON = (By.ID, 'saveBtn')
    CONFIRM_PASSWORD_ERROR = (By.XPATH, '//*[@id="changePassword"]/div[1]/div/div[3]/div/div[2]/div[2]')
    CURRENT_PASSWORD_ERROR = (By.XPATH, '//div[text() = "Please enter current password!"]')
    NEW_PASSWORD_ERROR = (By.XPATH, '//*[@id="changePassword"]/div[1]/div/div[2]/div/div[2]/div[2]/div')
    CURRENT_ASTRK = (By.XPATH, '(//span[@class = "required"])[1]')
    NEW_ASTRK = (By.XPATH, '(//span[@class = "required"])[2]')
    CONFIRM_ASTRK = (By.ID, 'asteriskConfirmPassword')


class CanonizerManageNickNameIdentifiersPage(object):
    CLICK_ON_DROPDOWN = (By.XPATH, '//*[@id="__next"]/div/header/div[3]/div[1]/div/div/div[2]/div/div[3]/a')
    ACCOUNT_SETTING_BUTTON = (By.XPATH, '(//span[@class="ant-dropdown-menu-title-content"])[1]')
    NICK_NAME = (By.XPATH, '(//div[@class="ant-tabs-tab-btn"])[4]')
    NICK_NAME_ID = (By.XPATH, '(//thead[@class="ant-table-thead"]//child::th[2])')
    VISIBILITY_STATUS = (By.XPATH, '(//thead[@class="ant-table-thead"]//child::th[4])')
    ADD_NEW_NICK_NAME = (By.XPATH, '//button[@class="ant-btn ant-btn-primary ant-btn ant-btn-orange ant-btn-lg"]')
    ADD_NEW_NICK_NAME_TITLE = (By.XPATH, '//div[text()="Add New Nick Name"]')
    POP_UP_NICK_NAME = (By.ID, 'enterNickName')
    POP_UP_CREATE_BUTTON = (By.ID, 'addEditBtn')
    POP_UP_NICK_NAME_ERROR = (By.XPATH, '//div[text()="Please Enter Nick Name!"]')
    SERIAL_NUMBER = (By.XPATH, '(//thead[@class="ant-table-thead"]//child::th[1])')
    CHECK_BOX = (By.XPATH, '//*[@id="login_form_remember"]')
    TITLE = (By.XPATH, '(//div[@class="ant-message-custom-content ant-message-error"]//child::span)[1]')
    FORGET_PASSWORD = (By.XPATH, '//a[text()= "Forgot password"]')
    TITTLE1 = (By.XPATH, '//h2[text()= "Forgot your password?"]')
    ERROR_NICK_NAME_EXISTS = (By.CLASS_NAME, 'ant-message-notice-content')


class ForgotPasswordIdentifiers(object):
    FORGOT_PASSWORD_LINK = (By.ID, 'forgot-password-link')
    LOGIN = (By.XPATH, '//span[text()=" Log In"]')
    FORGOT_PASSWORD = (By.XPATH, '//*[@id="login_form"]/div[3]/div/div/div/a')
    EMAIL = (By.ID, 'forgotPassword_email_id')
    SUBMIT_BUTTON = (By.XPATH, '(//span[text()="Submit "])[1]')
    OTP_PAGE_TITLE = (By.ID, 'forgot-password-title')
    FORGOT_PASSWORD_TITLE = (By.ID, 'forgot-password-title')
    INVALID_EMAIL = (By.XPATH, '//*[@id="forgotPassword"]/div[1]/div[2]/div[2]/div[2]/div')
    SUBMIT_OTP_BUTTON = (By.XPATH, '(//span[text()="Submit "])[1]')
    EMPTY_OTP = (By.XPATH, '//*[@id="otpverify"]/div[1]/div[2]/div/div[2]/div')
    OTP_ENTER = (By.XPATH, '//*[@id="otpverify_otp"]')
    INVALID_OTP = (By.XPATH, '//*[@id="otpverify"]/div[1]/div[2]/div/div[2]/div')
    CROSS_ICON_FORGOT_MODAL = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/button/span')
    CROSS_ICON_OTP_MODAL = (By.XPATH, '//*[@id="forgot-modal-close-btn"]/span/svg')
    CHANGE_PASSWORD_TITLE = (By.XPATH, '//h2[text()="Create new password"]')
    BLANK_EMAIL_ERROR = (By.XPATH, '//div[text()="Please input your E-mail!"]')


class CreateTopicIdentifiers(object):
    CREATE_NEW_TOPIC = (By.XPATH, '/html/body/div[1]/div/div[2]/div/aside/div/div[1]/button/span')
    LOGIN_PAGE = (By.ID, 'login-title')
    TOPIC_PAGE_TITLE = (By.XPATH, '(//span[text()="Create New Topic"])[1]')
    TOPIC_NAME = (By.ID, 'create_new_topic_topic_name')
    NICK_NAME = (By.ID, 'create_new_topic_nick_name')
    NAMESPACE = (By.ID, 'create_new_topic_namespace')
    EDIT_SUMMARY = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[2]/div/div/div[2]/div/div/textarea")
    CREATE_TOPIC_BUTTON = (By.ID, 'create-topic-btn')
    TOPIC_PAGE = (By.XPATH, '//h3[text()="Canonizer Sorted Camp Tree"]')
    BLANK_TOPIC_ERROR = (By.ID, "create_new_topic_topic_name_help")
    ERROR_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    ERROR_DUPLICATE_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    INVALID_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    CANCEL_BUTTON = (By.ID, 'cancel-btn')
    MAIN_PAGE = (By.XPATH, '//h3[text()="Select Namespace"]')
    NICK_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    TOPIC_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[2]')
    NAMESPACE_ASTERISK = (By.XPATH, '(//span[@class = "required"])[3]')


class UpdateTopicIdentifiers(object):
    MANAGE_EDIT_TOPIC_BUTTON = (By.XPATH, '/html/body/div[2]/div/div/ul/li[5]/span/a')
    TOPIC_HISTORY_TITLE = (By.XPATH, '//h4[text()="Topic History"]')
    TOPIC_NAME_ON_CURRENT_TOPIC_RECORD = (By.XPATH, '(//div[@class="ant-descriptions-item-container"]//span)[2]')
    TOPIC_NAME_ON_HISTORY_PAGE = (By.XPATH, '//div[contains(@class,"ant-typography mb-0")]//a[1]')
    SUBMITTER_NICK_NAME_LINK = (By.XPATH, '//h5[@class="ant-typography"]//a[1]')
    NICK_NAME_ON_PROFILE = (By.XPATH, '//span[@class="UserProfile_Bluecolor__El2lJ"]//b[1]')
    SUBMIT_UPDATE = (By.XPATH, '//div[@class="campHistory_campStatementCollapseButtons__LVwiX"]//button[1]')
    TOPIC_UPDATE_TITLE = (By.XPATH, '//div[text()="Topic Update"]')
    UPDATE_TOPIC_NAME = (By.ID, 'topic_name')
    SUBMIT_UPDATE_BUTTON = (By.XPATH, '//div[@class="ant-form-item-control-input-content"]//button[1]')
    DUPLICATE_TOPIC_NAME_ERROR = (By.XPATH, '/html/body/div[2]/div/div/div/div')
    CANCEL_BUTTON = (By.XPATH,'(//div[@class="ant-form-item-control-input-content"]//button)[2]')
    PREVIEW_BUTTON = (By.XPATH, '(//div[@class="ant-form-item-control-input-content"]//button)[3]')
    TOPIC_PREVIEW_TITLE = (By.XPATH,'//div[text()="Topic Preview"]')
    SUBMITTER_NICK_NAME_LINK_ON_PREVIEW_MODAL = (By.XPATH, '//span[@class="ant-descriptions-item-content"]//a[1]')
    CANCEL_PREVIEW_BUTTON = (By.XPATH, '//div[@class="ant-modal-footer"]//button[1]')
    COMPARE_CHECKBOX1 = (By.XPATH, '/html/body/div/div/div[2]/div/div/div[3]/div[2]/div/div/div[1]/div/div/div/div[2]/div[1]/label/span[1]/input')
    COMPARE_CHECKBOX2 = (By.XPATH, '(/html/body/div/div/div[2]/div/div/div[3]/div[2]/div/div/div[2]/div/div/div/div[2]/div[1]/label/span[1]/input')
    COMPARE_TOPIC_BUTTON = (By.ID, 'compare-topic')
    TOPIC_HISTORY_COMPARISON_TITLE = (By.XPATH, '//h4[text()="Topic "]')
    AGREEMENT_LINK = (By.XPATH, '//div[@class="topicDetails_breadcrumbLinks__7BG2D"]//a[1]')
    CREATE_TOPIC = (By.ID, 'create-topic-btn')
    CREATE_CAMP = (By.ID, 'create-camp-btn')
    BACK_ARROW_ICON = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div[3]/div[1]/div/button')
    VIEW_THIS_VERSION_BUTTON = (By.XPATH, '//button[contains(@class,"ant-btn ant-btn-primary")]//a')


class CampForumIdentifiers(object):
    VIEW_ALL = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/div/div/div[1]/div/div[1]/div/div/div[3]/div/div/a/span')
    CAMP_FORUM_BUTTON = (By.ID, 'camp-forum-btn')
    BROWSE = (By.XPATH, '//*[@id="__next"]/div/header/div[2]/nav/ul/li[1]/a')
    SEARCH_TOPIC = (By.XPATH, '//input[@placeholder="Search by topic name"]')
    SEARCH_ICON = (By.XPATH, '(//span[@class="ant-input-group-addon"]//button)[2]')
    TOPIC_CLICK = (By.XPATH, '//li[@class="ant-list-item topicsList_item__toE6c"]//a[1]')

    CAMP_FORUM_TITLE = (By.CLASS_NAME, 'Forum_cardTitle__VagbD')
    MY_PARTICIPATION = (By.ID, 'participate-btn')
    TOP_10_THREADS = (By.ID, 'most-rep-btn')
    NO_THREAD_STATEMENT = (By.XPATH, '//div[text()="No Data"]')
    ALL_THREADS_BUTTON = (By.ID, 'all-thread-btn')
    MY_THREADS_BUTTON = (By.ID, 'my-thread-btn')
    THREAD_BUTTON = (By.ID, 'all-thread-btn')
    CREATE_THREAD_BUTTON = (By.XPATH, '/html/body/div/div/div[2]/div/div/div[2]/div/div/div[2]/div[1]/button[5]/span')
    CREATE_THREAD_TITLE = (By.XPATH, '//span[text()="Create a new thread"]')
    THREAD_TITLE = (By.ID, 'create_new_thread_thread_title')
    NICK_NAME = (By.XPATH, '//div[text()="sania_talentelgia"]')
    SUBMIT_THREAD = (By.ID, 'submit-btn')
    THREAD_BACK = (By.ID, 'back-btn')
    ERROR_BLANK_TITLE = (By.XPATH, '//*[@id="create_new_thread"]/div/div/div[1]/div[2]/div[2]/div')
    DUPLICATE_TITLE_ERROR = (By.XPATH, '/html/body/div[2]/div/div/div/div')
    THREAD_TITLE_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    NICK_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[2]')
    BACK_BUTTON = (By.ID, 'back-btn')
    EDIT_THREAD_ICON = (By.XPATH, '//a[@class="Forum_threadListTitle__eSVW8"]//a[1]')
    EDIT_THREAD_PAGE_TITLE = (By.XPATH, '//span[text()="Edit title of the thread"]')
    THREAD_LINK = (By.ID, 'thread-label-1')
    POST_TITLE = (By.ID, 'card-title')
    POST_REPLY = (By.XPATH, '//*[@id="new_post"]/div/div[1]/div/div/div[2]/div[1]')
    POST_NICK_NAME = (By.XPATH, '//*[@id="new_post"]/div/div[2]/div/div[2]/div[1]/div/div')
    POST_SUBMIT = (By.ID, 'submit-btn')
    REPLY_FIELD = (By.CLASS_NAME, 'ql-editor')
    EMPTY_REPLY_ERROR = (By.XPATH, '//span[@class="ant-typography ant-typography-danger"]')
    NICK_NAME_LINK_ON_POST_PAGE = (By.XPATH, '//*[@id="started-by-label"]/a')
    USER_PROFILE_TITLE = (By.XPATH, '//div[@class="ant-card-head-wrapper"]//div')
    EDIT_REPLY = (By.XPATH, '(//div[@class="ant-space-item"]//a)[3]')
    REPLY_UPDATED_MESSAGE = (By.XPATH, '//div[@class="ant-message-notice"]//div')
    DELETE_REPLY = (By.XPATH, '//a[@id="post-delete-icon-1938"]')
    BUTTON2 = (By.XPATH, '/html/body/div[2]/div/div/div/div[2]/div/div[2]/button[2]')
    EDIT_POST_ICON = (By.XPATH, '(//div[@class="ant-space-item"]//a)[3]')
    VERIFY_POST_REPLY = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/p[1]')
    POST_UPDATE_MESSAGE = (By.XPATH, '/html/body/div[3]/div/div/div/div')
    DELETE_POST_ICON = (By.XPATH, '(//a[@class="linkCss"])[2]')
    DELETE_CONFIRM = (By.XPATH, '(//div[@class="ant-popover-buttons"]//button)[2]')
    POST_DELETE_MESSAGE = (By.XPATH, '/html/body/div[2]/div/div/div/div')


class HomePageIdentifiers(object):
    FACEBOOK_LINK = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[3]/div[1]/div/a[1]/span/img')
    INSTA_LINK = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[3]/div[1]/div/a[2]/span/img')
    TWITTER_LINK = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[3]/div[1]/div/a[3]/span/img')
    YOUTUBE_LINK = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[3]/div[1]/div/a[4]/span/img')
    LINKEDIN_LINK = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[3]/div[1]/div/a[5]/span/img')
    PRIVACY_POLICY = (By.XPATH, '//a[text() = "Privacy Policy"]')
    TERMS_AND_SERVICES = (By.XPATH, '//a[text() = "Terms & Services"]')
    BROWSE = (By.XPATH, '//i[@class = "icon-angle-right"]')
    CREATE_NEW_TOPIC = (By.XPATH, '(//i[@class = "icon-angle-right"])[4]')
    UPLOAD_FILE = (By.XPATH, '(//i[@class = "icon-angle-right"])[5]')
    HELP = (By.XPATH, '(//i[@class = "icon-angle-right"])[6]')
    WHITE_PAPER = (By.XPATH, '(//i[@class = "icon-angle-right"])[7]')
    BLOG = (By.XPATH, '(//i[@class = "icon-angle-right"])[8]')
    JOBS = (By.XPATH, '(//i[@class = "icon-angle-right"])[9]')
    CANONIZER_LOGO = (By.XPATH, '//*[@id="__next"]/div/footer/div[1]/div/div[1]/div/a/span/img')
    SUPPORT_CANONIZER = (By.XPATH, 'icon-envelope')
    ALGORITHM_DROP_DOWN = (By.XPATH,'//div[contains(@class,"ant-select ant-select-lg")]//div')


class CreateCampIdentifiers(object):
    CREATE_NEW_CAMP_BUTTON = (By.XPATH, '/html/body/div/div/div[2]/div/div[1]/aside/div[1]/div[1]/button[2]/span')
    NEW_CAMP_TITLE = (By.ID, 'card-title')
    NICK_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    PARENT_CAMP_ASTERISK = (By.XPATH, '(//span[@class="required"])[2]')
    CAMP_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[3]')
    CAMP_NICKNAME = (By.ID, 'nickname-dropdown')
    PARENT_CAMP = (By.ID, 'parent-camp-dropdown')
    CAMP_NAME = (By.ID, 'create_new_camp_camp_name')
    CAMP_EDIT_SUMMARY = (By.ID, 'create_new_camp_note')
    CAMP_ABOUT_URL = (By.ID, 'create_new_camp_camp_about_url')
    KEYWORDS = (By.ID, 'create_new_camp_key_words')
    CAMP_ABOUT_NICK_NAME = (By.XPATH, '(//div[@class="ant-select-selector"])[3]')
    CREATE_CAMP_BUTTON = (By.ID, 'crate-camp-btn')
    CAMP_CANCEL_BUTTON = (By.ID, 'cancel-btn')
    TOPIC_PAGE_TITLE = (By.XPATH, '//span[text()="Camp created successfully."]')
    BLANK_CAMP_NAME_ERROR = (By.XPATH, '//div[@class="ant-form-item-explain ant-form-item-explain-connected"]//div[1]')
    DUPLICATE_CAMP_NAME_ERROR = (By.XPATH, '//div[text()="The camp name has already been taken."]')
    INVALID_CAMP_ABOUT_URL_ERROR = (By.XPATH, '//div[text()="The camp about url format is invalid. (Example: https://www.example.com?post=1234)"]')
    CANCEL_BUTTON = (By.ID, 'cancel-btn')
    MANAGE_EDIT_CAMP_BUTTON = (By.XPATH, '/html/body/div[2]/div/div/ul/li[6]/span[2]')
    CAMP_HISTORY_TITLE = (By.XPATH, '//h4[@class="ant-typography"]')
    CAMP_NAME_CLICK = (By. XPATH, '(//span[@class="treeListItemTitle topicDetails_treeListItemTitle__G91mC"]//a)[3]')
    SUBMITTER_NICK_NAME_LINK = (By.XPATH, '//h5[@class="ant-typography"]//a[1]')
    USER_PROFILE_NICK_NAME_VERIFY = (By.XPATH, '//span[@class="UserProfile_Bluecolor__El2lJ"]//b[1]')
    SUBMIT_CAMP_UPDATE = (By.XPATH, '//span[text()="Submit Camp Update Based On This"]')
    CAMP_UPDATE_PAGE_TITLE = (By.XPATH, '//div[text()="Camp Update"]')
    EDIT_CAMP_NAME_FIELD = (By.ID, 'camp_name')
    SUBMIT_UPDATE_BUTTON = (By.XPATH, '(//button[@type="submit"]//span)[2]')
    CANCEL_CAMP_UPDATE_BUTTON = (By.XPATH, '//button[contains(@class,"ant-btn ant-btn-default")]/following-sibling::button[1]')
    PREVIEW_BUTTON = (By.XPATH, '(//button[contains(@class,"ant-btn ant-btn-primary")]//span)[2]')
    PREVIEW_CANCEL_BUTTON = (By.XPATH, '(//button[@class="ant-btn ant-btn-default"])[2]')
    CAMP_HISTORY = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div[3]/div[2]/div/div/div[1]/div/div/div')
    EDIT_CAMP_URL = (By.ID, 'camp_about_url')
    EDIT_SUMMARY = (By.ID, 'edit_summary')
    EDIT_KEYWORDS = (By.ID, 'keywords')
    EDIT_PARENT_CAMP = (By.XPATH, '(//div[contains(@class,"ant-select ant-select-lg")]//div)[2]')
    EDIT_NICK_NAME = (By.XPATH, '//div[contains(@class,"ant-select ant-select-lg")]//div')
    PREVIEW_TITLE = (By.ID, 'rc_unique_0')
    PREVIEW_SUBMIT = (By.XPATH, '(//div[@class="ant-modal-footer"]//button)[2]')
    PREVIEW_CAMP_NAME_VERIFY = (By.XPATH, '(//div[@class="ant-descriptions-item-container"]//span)[2]')
    PREVIEW_KEYWORD_VERIFY = (By.XPATH, '//span[text()="Keywords"]/following-sibling::span')
    PREVIEW_CAMP_ABOUT_URL_VERIFY = (By.XPATH, '(//span[@class="ant-descriptions-item-label"]/following-sibling::span)[3]')
    PREVIEW_EDIT_SUMMARY_VERIFY = (By.XPATH, '//span[text()="Edit Summary"]/following-sibling::span')
    PREVIEW_NICK_NAME_VERIFY = (By.XPATH, '(//span[@class="ant-descriptions-item-content"]//a)[3]')
    COMPARE_CHECKBOX1 = (By.XPATH, '//span[@class="ant-checkbox"]/following-sibling::span')
    COMPARE_CHECKBOX2 = (By.XPATH, '(//span[@class="ant-checkbox"]/following-sibling::span)[2]')
    COMPARE_CAMP_BUTTON = (By.ID, 'compare-camp')
    CAMP_HISTORY_COMPARISON = (By.XPATH, '//button[@class="ant-btn ant-btn-primary"]/following-sibling::h4[1]')
    CAMP_NAME1 = (By.XPATH, '//div[@class="ant-collapse-content-box"]//span')
    CAMP_NAME2 = (By.XPATH, '(//div[@class="ant-collapse-content-box"]//span)[2]')
    COMPARE_CAMP1 = (By.XPATH, '//ins[@class="diffmod"]')
    COMPARE_CAMP2 = (By.XPATH, '(//ins[@class="diffmod"])[2]')
    CANCEL_TITLE = (By.XPATH, '/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[1]/span/h3')

class AddNewsIdentifiers(object):
    ADD_NEWS_LINK = (By.XPATH, '//div[@class="ant-checkbox-wrapper"]//a[1]')
    ADD_NEWS_PAGE_TITLE = (By.XPATH, '//div[text()="Add News"]')
    DISPLAY_TEXT = (By.ID, 'display_text')
    LINK = (By.ID, 'link')
    NICKNAME = (By.XPATH, '//span[@title="sania_talentelgia"]')
    CREATE_NEWS_BUTTON = (By.ID, 'create-news-btn')
    CANCEL_BUTTON = (By.ID, 'cancel-news-btn')
    DISPLAY_TEXT_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    LINK_ASTERISK = (By.XPATH, '(//span[@class="required"])[2]')
    NICKNAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[3]')
    NEWS_ADDED = (By.XPATH, '//h4[text()="News added by sania_talentelgia"]')
    BLANK_LINK_ERROR = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div/div/div/div[2]/form/div[1]/div[2]/div[1]/div[2]/div[2]/div')
    BLANK_DISPLAY_TEXT_ERROR = (By.XPATH, '//div[@role="alert"]')
    TOPIC_PAGE = (By.XPATH, '//h3[text()="Canonizer Sorted Camp Tree"]')
    AVAILABLE_FOR_CHILD_CAMP = (By.ID, 'available_for_child')
    INVALID_LINK = (By.XPATH, '//span[@class="ant-typography ant-typography-danger"]')
    EDIT_NEWS = (By.XPATH, '//div[@class="ant-checkbox-wrapper"]//button[1]')
    EDIT_ICON = (By.ID, 'news-edit-btn')
    EDIT_NEWS_TITlE = (By.XPATH, '//div[@class="ant-card-head-wrapper"]//div[1]')
    EDIT_CANCEL_BUTTON = (By.ID, 'cancel-news-btn')


class LogoutIdentifiers(object):
    LOGOUT = (By.XPATH, '//span[text()="Log Out"]')
    CLICK_ON_DROPDOWN = (By.XPATH, '(//div[contains(@class,"ant-space ant-space-horizontal")])[3]')


class CampStatementIdentifiers(object):
    ADD_STATEMENT_BUTTON = (By.ID, "add-camp-statement-btn")
    ADD_STATEMENT_TITLE = (By.XPATH, '//div[text()="Add Camp Statement"]')
    NICK_NAME = (By.XPATH, '(//div[@class="ant-select-selector"]//span)[2]')
    SELECTED_NAMESPACE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/div/div[2]/div/div/div/div/span[2]")
    NAMESPACE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/div/div[2]/div/div/div/div/span[2]")
    STATEMENT = (By.ID, 'statement')
    CAMP_STATEMENT_ASTERISK1 = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div[2]/div/div[2]/form/div/div[1]/div/div/div[1]/label/span")
    CAMP_STATEMENT_ASTERISK2 = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div[2]/div/div[2]/form/div/div[2]/div/div/div[1]/label/span")
    EDIT_SUMMARY = (By.ID, 'edit_summary')
    SUBMIT_STATEMENT_BUTTON = (By.ID, "update-submit-btn")
    UPDATE_CANCEL_BUTTON = (By.ID, "update-cancel-btn")
    STATEMENT_TEXT = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div[2]/div/div[2]/form/div/div[2]/div/div/div[2]/div/div/div/div[2]/div/div/div")
    CANCEL_BUTTON = (By.XPATH, '//button[contains(@class,"ant-btn ant-btn-ghost")]')
    CAMP_STATEMENT_HISTORY = (By.XPATH, '//h4[@class="ant-typography"]')
    NICK_NAME_ASTERISK = (By.XPATH, '//span[@class="required"]')
    STATEMENT_ASTERISK = (By.XPATH, '(//span[@class="required"])[2]')
    STATEMENT_FIELD_ERROR = (By.XPATH, 'ant-form-item-explain-error')
    TOPIC_PAGE = (By.XPATH, '//h3[text()="Canonizer Sorted Camp Tree"]')
    PREVIEW_PAGE = (By.XPATH, '(//button[contains(@class,"ant-btn ant-btn-primary")])[2]')
    SUBMIT_PREVIEW = (By.XPATH, '//button[@class="ant-btn ant-btn-primary"]')
    PREVIEW_MODAL_TITLE = (By.XPATH, '//div[text()="Statement Preview"]')
    EDIT_CAMP_STATEMENT_BUTTON = (By.XPATH, '//button[contains(@class,"ant-btn ant-btn-default")]//a')
    CAMP_HISTORY_TITLE = (By.XPATH, '//h4[@class="ant-typography"]')
    SUBMIT_STATEMENT_UPDATE = (By.XPATH, '//span[text()="Submit Statement Update Based on This"]')
    SUBMIT_UPDATE = (By.XPATH, '(//button[@type="submit"])[2]')
    VIEW_THIS_VERSION_BUTTON = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div[3]/div[2]/div/div/div[1]/div/div/div/div[2]/div[2]/button[2]')
    OBJECTED_COLOR = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]')
    LIVE_COLOR = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]')
    IN_REVIEW = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]')
    OLD = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[5]/div[1]/div[1]/div[1]')
    COMPARE_STATEMENT2 = (By.XPATH, '//div[@id="__next"]/div[1]/div[3]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/label[1]/span[2]')
    COMPARE_STATEMENT1 = (By.XPATH, '(//label[@class="ant-checkbox-wrapper campHistory_campSelectCheckbox__NNUPk"]//span)[3]')
    COMPARE_STATEMENT_BUTTON = (By.ID, 'compare-statement')
    STATEMENT_COMPARE_HISTORY_TITLE = (By.XPATH, '//div[@class="UI_filterOt___p9MH"]//h4[1]')


class CampHistoryIdentifiers(object):
    THREEDOTS = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div[1]/div[1]/div/div/div[2]/div/a/span")
    TOPIC_EDIT_BUTTON = (By.XPATH, '//a[@href="/topic/history/173-Software-Testing"]')
    CAMP_EDIT_BUTTON = (By.XPATH, '/html/body/div[2]/div/div/ul/li[4]/span')
    TOPIC_HISTORY_TITLE = (By.XPATH, '//h4[@class="ant-typography"]')
    HISTORY_TOPIC = (By.XPATH, '//a[@href="/topic/173-Software-Testing/1-Agreement"]')
    NAMESPACE_ALL = (By.XPATH, '//div[@title="All"]//div[1]')
    MANAGE_EDIT_CAMP_BUTTON = (By.XPATH, '/html/body/div[2]/div/div/ul/li[6]/span[2]')
    NAMESPACE = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div/div/div/div[1]/div/div/div[1]/div/div[1]/div')
    ARCHIEVED = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div[2]/div/div/div/div/div[1]/div/div[2]/label[3]/span[1]")
    ARCHIEVED_EDIT = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div[2]/div/div[1]/div/div[2]/label[3]/span[1]")
    ARCHIEVED_STATUS = (By.XPATH, "/html/body/div/div/div[2]/div/div/div[3]/div[2]/div/div/div/div/div/div/div[2]/div[1]/h5[8]/span")
    ARCHIVED_SCORE = (By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[2]/span[3]/span/div/div/span[3]/div/div/div/span")
    CAMP_EDIT_SUBMIT = (By.ID, "update-submit-btn")


class CampForumIdentifiers(object):
    VIEW_ALL = (By.XPATH, '//*[@id="__next"]/div/div[2]/div/div/div/div[1]/div/div[1]/div/div/div[3]/div/div/a/span')
    CAMP_FORUM_BUTTON = (By.ID, 'camp-forum-btn')
    BROWSE = (By.XPATH, '/html/body/div/div/header/div[2]/nav/ul/li[1]/a')
    SEARCH_TOPIC = (By.XPATH, '//input[@placeholder="Search by topic name"]')
    SEARCH_ICON = (By.XPATH, '(//span[@class="ant-input-group-addon"]//button)[2]')
    TOPIC_CLICK = (By.XPATH, '/html/body/div/div/div[2]/div/div/div/div/div/div[1]/div[2]/div/ul/li/a/span[1]')
    CAMP_FORUM_TITLE = (By.XPATH, '/html/body/div/div/div[2]/div/div/div[2]/div/div/div[1]/div/div[1]/span')
    THREAD_BUTTON = (By.ID, 'all-thread-btn')
    
    
class CreateTopicIdentifiers(object):
    CREATE_NEW_TOPIC = (By.XPATH, "/html/body/div[1]/div/div[2]/div/aside/div/div[1]/button/span")
    LOGIN_PAGE = (By.XPATH, '//h2[text() = "Login to Canonizer"]')
    TOPIC_PAGE_TITLE = (By.XPATH, '(//span[text()="Create New Topic"])[1]')
    TOPIC_NAME = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div/input")
    NICK_NAME = (By.ID, 'create_new_topic_nick_name')
    NAMESPACE = (By.ID, 'create_new_topic_namespace')
    SELECTED_TITLE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/div/div[2]/div/div/div/div/span[2]")
    EDIT_SUMMARY = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[2]/div/div/div[2]/div/div/textarea")
    CREATE_TOPIC_BUTTON = (By.ID, 'create-topic-btn')
    TOPIC_PAGE = (By.XPATH, '//h3[text()="Canonizer Sorted Camp Tree"]')
    ERROR_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    ERROR_DUPLICATE_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    INVALID_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    CANCEL_BUTTON = (By.ID, 'cancel-btn')
    MAIN_PAGE = (By.XPATH, '//h3[text()="Select Namespace"]')
    NICK_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    TOPIC_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[2]')
    NAMESPACE_ASTERISK = (By.XPATH, '(//span[@class = "required"])[3]')

class SupportValueIdentifiers(object):
    CREATE_NEW_TOPIC = (By.XPATH, "/html/body/div[1]/div/div[2]/div/aside/div/div[1]/button/span")
    LOGIN_PAGE = (By.XPATH, '//h2[text() = "Login to Canonizer"]')
    TOPIC_PAGE_TITLE = (By.XPATH, '(//span[text()="Create New Topic"])[1]')
    TOPIC_NAME = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div/input")
    NICK_NAME = (By.ID, 'create_new_topic_nick_name')
    NAMESPACE = (By.XPATH, '/html/body/div[1]/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/div/div[2]/div/div/div')
    TOPIC_DETAIL = (By.XPATH, "//html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div/span[2]/span")
    START_NEW_CAMP = (By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[2]/span[3]/span")
    START_SECOND_NEW_CAMP = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[3]/span[3]/span")
    SELECTED_TITLE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[1]/div[3]/div/div[2]/div/div/div/div/span[2]")
    CAMP_NAME = (By.ID, "create_new_camp_camp_name")
    CAMP_KEYWORD = (By.ID, "create_new_camp_key_words")
    CAMP_NOTE = (By.ID, "create_new_camp_note")
    CAMP_ABOUT_URL = (By.ID, "create_new_camp_camp_about_url")
    NICK_NAME_DROPDOWN = (By.ID, "camp-about-nick-dropdown")
    SELECT_NICK_NAME = (By.ID, "camp-about-nick-301")
    CREATE_CAMP = (By.ID, "crate-camp-btn")
    MANAGE_SUPPORT = (By.ID, "manage-support-btn")
    SUPPORT_SUBMIT_BUTTON = (By.ID, "uploadBtn")
    TOPIC_SCORE = (By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[1]/span[3]/span/div/div/span[3]/div/div/div/span")
    CAMP1_SCORE = (By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[2]/span[3]/span/div/div/span[3]/div/div/div/span")
    CAMP2_SCORE = (By.XPATH, "/html/body/div/div/div[2]/div/div[1]/div[2]/div[1]/div/div[2]/div/div/div[3]/div/div/div/div[3]/span[3]/span/div/div/span[3]/div/div/div/span")
    EDIT_SUMMARY = (By.XPATH, "/html/body/div/div/div[2]/div/div/div/div/div/div[2]/form/div[1]/div[2]/div/div/div[2]/div/div/textarea")
    CREATE_TOPIC_BUTTON = (By.ID, 'create-topic-btn')
    TOPIC_PAGE = (By.XPATH, '//h3[text()="Canonizer Sorted Camp Tree"]')
    ERROR_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    ERROR_DUPLICATE_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    INVALID_TOPIC_NAME = (By.XPATH, '//*[@id="create_new_topic"]/div/div[1]/div[2]/div[2]/div[2]/div')
    CANCEL_BUTTON = (By.ID, 'cancel-btn')
    MAIN_PAGE = (By.XPATH, '//h3[text()="Select Namespace"]')
    NICK_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])')
    TOPIC_NAME_ASTERISK = (By.XPATH, '(//span[@class = "required"])[2]')
    NAMESPACE_ASTERISK = (By.XPATH, '(//span[@class = "required"])[3]')
class UploadFileIdentifiers(object):
    """
    Class to hold the Browse Page Identifiers
    """
    UPLOADFILE = (By.XPATH, '//*[@id="__next"]/div/header/div[2]/nav/ul/li[2]/a')
    UPLOAD = (By.XPATH, '/html/body/div/div/div[2]/div/div/div/div/form/div/div[2]/div[1]/span/div[1]/span/input')
    UPLOADBUTTON = (By.XPATH, '/html/body/div[1]/div/header/div[2]/nav/ul/li[2]/a')
    ERROR_FILE_NAME = "  "
    FIVE_MB_FILE = "/home/akashroshan/PycharmProjects/Test/5mb.jpg"
    VALID_FILE_NAME = "/home/akashroshan/PycharmProjects/Test/sample.csv"
    UPLOADED_OPTION = (By.ID, "threeDots")
    UPLOADED_IMAGE = (By.XPATH, "/html/body/div[1]/div/div[3]/div/div/div/div/form/div/div[2]/div[2]/div[1]/div/div/div/h3/span[1]")
    UPLOADED_IMAGE_VIEW = (By.XPATH, '/html/body/div[2]/div/div/ul/li[1]/span/span/span[2]')
    
class ForgotPasswordIdentifiers(object):
    FORGOT_PASSWORD_LINK = (By.ID, 'forgot-password-link')
    LOGIN = (By.XPATH, '/html/body/div/div/header/div[3]/div[1]/button[1]/span')
    FORGOT_PASSWORD = (By.XPATH, '/html/body/div[2]/div/div[2]/div/div[2]/div/div/div/section/div/div[1]/div/form/div[3]/div/div/div/div/a')
    EMAIL = (By.ID, 'forgotPassword_email_id')
    SUBMIT_BUTTON = (By.ID, 'submit-btn')
    OTP_PAGE_TITLE = (By.ID, 'forgot-password-title')
    FORGOT_PASSWORD_TITLE = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/h2')
    INVALID_EMAIL = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div')
    SUBMIT_OTP_BUTTON = (By.ID, 'submit-btn')
    EMPTY_OTP = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/div[1]/div[2]/div[1]/div/div[2]/div[1]/div')
    OTP_ENTER = (By.ID, 'otpverify_otp')
    INVALID_OTP = (By.XPATH, '/div/div/div/span[2]')
    CROSS_ICON_FORGOT_MODAL = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/button/span/svg')
    CROSS_ICON_OTP_MODAL = (By.XPATH, '/html/body/div[3]/div/div[2]/div/div[2]/div/div/div/section/form/button/span/svg')
    CHANGE_PASSWORD_TITLE = (By.XPATH, '//h2[text()="Create new password"]')
    
class BrowsePageIdentifiers(object):
    """
    Class to hold the Browse Page Identifiers
    """
    BROWSE = (By.XPATH, '/html/body/div[1]/div/header/div[2]/nav/ul/li[1]/a/text()')
    ONLY_MY_TOPICS = (By.XPATH, '/html/body/div/div/div[2]/div/div/div/div/div/div[1]/div[1]/div/label/span[1]')
    NAMESPACE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[1]/div[1]/div/div[1]")
    GENERAL = (By.ID, 'name-space-1')
    SELECTED_TITLE = (By.XPATH, "/html/body/div[1]/div/div[2]/div/div/div/div/div/div[1]/div[1]/div/div[1]/div/span[2]")
    CORPORATIONS = (By.ID, 'name-space-2')
    CRYPTOCURRENCY = (By.ID, 'name-space-3')
    FAMILY = (By.ID, 'name-space-4')
    FAMILYJESPERSON = (By.ID, 'name-space-5')
    OCCUPYWALLSTREET = (By.ID, 'name-space-6')
    ORGANIZATION = (By.ID, 'name-space-7')
    ORGANIZATIONCANONIZER = (By.ID, 'name-space-8')
    ORGANIZATIONCANONIZERHELP =  (By.ID, 'name-space-9')
    ORGANIZATIONMTA = (By.ID, 'name-space-10')
    ORGANIZATIONTV07 = (By.ID, 'name-space-11')
    ORGANIZATIONWTA = (By.ID, 'name-space-12')
    PERSONALATTRIBUTE = (By.ID, 'name-space-13')
    PERSONALREPUTATION = (By.ID, 'name-space-14')
    PROFESSIONALSERVICES = (By.ID, 'name-space-15')
    SANDBOX = (By.ID, 'name-space-16')
    TERMINOLOGY = (By.ID, 'name-space-17')
    WWW = (By.ID, 'name-space-18')
    SANDBOXTESTING = (By.ID, 'name-space-19')
    CRYPTOCURRENCYETHEREUM = (By.ID, 'name-space-21')
    VOID = (By.ID, 'name-space-22')
    MORMONCANONPROJECT = (By.ID, 'name-space-24')
    ORGANIZATIONUNITEDUTAHPARTY = (By.ID, 'name-space-25')
    GOVERNMENT = (By.ID, 'name-space-26')
    GOVERNMENTSANDYCITY = (By.ID, 'name-space-27')
    SPORT = (By.ID, 'name-space-28')
    SPORTSBCL = (By.ID, 'name-space-29')
    PLATEFORMOFTHEPEOPLE = (By.ID, 'name-space-30')
    FICTION = (By.ID, 'name-space-31')
    FICTIONLORDOFTHERINGS = (By.ID, 'name-space-32')
    FICTIONSTARWARS = (By.ID, 'name-space-33')
    FICTIONWORLDOFWARCRAFT = (By.ID, 'name-space-34')
    ALL = (By.ID, 'name-space-custom')

    UPLOADFILE = (By.XPATH, '//*[@id="__next"]/div/header/div[2]/nav/ul/li[2]/a')
    MENU_ITEM = (By.ID, 'namespace')
    TOPIC_NAME = (By.XPATH, '//*[@id="outline_127"]/a')
    UPLOAD = (By.XPATH, '//*[@id="__next"]/div/header/div[2]/nav/ul/li[2]/a')
    TITLE = (By.XPATH, '/html[1]/body[1]/div[1]/div[1]/header[1]/div[1]/a[1]/span[1]/img[1]')
    HEADING = (By.XPATH, '//*[@id="__next"]/div/div[3]/div/div/div/div/div/div[1]/div/div/div[1]/div/h3/text()')
    
class UploadFileIdentifiers(object):
    """
    Class to hold the Browse Page Identifiers
    """
    UPLOADFILE = (By.XPATH, '//*[@id="__next"]/div/header/div[2]/nav/ul/li[2]/a')
    UPLOAD = (By.XPATH, '/html/body/div/div/div[2]/div/div/div/div/form/div/div[2]/div[1]/span/div[1]/span/input')
    UPLOADBUTTON = (By.XPATH, '/html/body/div[1]/div/header/div[2]/nav/ul/li[2]/a')
    UPLOADBUTTON_ID = (By.ID, "uploadBtn")
    ERROR_FILE_NAME = "  "
    ENTER_FILE_NAME = (By.ID, "enterFileName")
    ADD_FILE_BUTTON = (By.ID, 'addAFileBtn')
    FIVE_MB_FILE = "/home/akashroshan/PycharmProjects/Test/5mb.jpg"
    VALID_FILE_NAME = "/home/akashroshan/PycharmProjects/Test/sample.csv"
    UPLOADED_OPTION = (By.ID, "threeDots")
    UPLOADED_IMAGE = (By.XPATH, "/html/body/div[1]/div/div[3]/div/div/div/div/form/div/div[2]/div[2]/div[1]/div/div/div/h3/span[1]")
    UPLOADED_IMAGE_VIEW = (By.XPATH, '/html/body/div[2]/div/div/ul/li[1]/span/span/span[2]')

class CanonizerFooterIdentifiers(object):
    FOOTER_BROWSE = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[1]/ul/li[1]/a")
    FOOTER_NEW_TOPIC = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[1]/ul/li[2]/a/i")
    FOOTER_UPLOAD = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[1]/ul/li[3]/a")
    FOOTER_SITEMAP = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[1]/ul/li[4]/a/i")
    FOOTER_HELP = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[2]/ul/li[1]/a/i")
    FOOTER_WHITEPAPER = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[2]/ul/li[2]/a/i")
    FOOTER_BLOG = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[2]/ul/li[3]/a/i")
    FOOTER_JOBS = (By.XPATH, "/html/body/div/div/footer/div[1]/div/div[2]/div/div/div[2]/ul/li[4]/a/i")
